Get request
arikhativa/webserv pull request #94
Opened 2023-08-30 16:19 UTC by llanahp

2023-09-06 10:23 UTC, arikhativa requested changes
it looks good. there are a few notes, but it has a good structure :)

2023-09-06 10:23 UTC, arikhativa commented on src/class/HTTPCall/HTTPCall.cpp
> +	Path serverPath(this->_virtual_server->getConf()->getRoot()->get());
this is not so simple.
the path might be the path inside Location.
e.g.
```
server {
  root /var/www/html
  
  location /upload {
    root /tmp
  }
}
```

2023-09-06 10:23 UTC, arikhativa commented on src/class/HTTPCall/HTTPCall.cpp
> +	Path serverPath(this->_virtual_server->getConf()->getRoot()->get());
i think it is best to move this logic to matcher namespace and have something like `Path matcher::rootToRequest(Server, Location, BasicHTTPRequest)`

inside, if the root is not in the location, then we take the one from server

2023-09-06 10:23 UTC, arikhativa commented on src/class/HTTPCall/HTTPCall.cpp
> +std::list<const ILocation *>::const_iterator HTTPCall::searchMatchLocation(void) const
i wrote this logic in matcher namespace

2023-09-06 10:23 UTC, arikhativa commented on src/class/HTTPCall/HTTPCall.cpp
> +bool HTTPCall::isAutoIndexOn(void) const
i think HTTPCall should have the IServer and ILocation as private vars.
we can get them with matcher after we read the client's call.
no need to look for them every time

2023-09-06 10:23 UTC, arikhativa commented on src/class/HTTPCall/HTTPCall.cpp
> +bool HTTPCall::canUpload(void) const
same

2023-09-06 10:23 UTC, arikhativa commented on src/code/HTTPRequestHandler/HTTPRequestHandler.cpp
> +		BasicHTTPRequest requestRecived = request.getBasicRequest();
i think HTTPCall have it's own BasicHTTPRequest. no need to create here a new one

2023-09-06 10:23 UTC, arikhativa commented on src/code/HTTPRequestHandler/HTTPRequestHandler.cpp
> +			ResponseHeader response(HTTPStatusCode(HTTPStatusCode::OK), request.getErrorPages());
nice flow, maybe split into a static func isDirectoryListing()?

2023-09-06 10:23 UTC, arikhativa commented on src/code/HTTPRequestHandler/HTTPRequestHandler.cpp
> +	catch (const BasicHTTPRequest::Incomplete &e)
if it is incomple then we need to read more from client till timeout

2023-09-06 10:23 UTC, arikhativa commented on src/code/HTTPRequestHandlerGET/HTTPRequestHandlerGET.cpp
> +bool httprequesthandlerGET::isFileExists(const std::string &path)
why not just use FileManager directly?

2023-09-07 17:37 UTC, dVaGaymer approved these changes

2023-09-11 07:27 UTC, arikhativa requested changes

2023-09-11 07:27 UTC, arikhativa commented on src/code/matcher/matcher.cpp
> +Path matcher::rootToRequest(const Server *server, const BasicHTTPRequest &req)
the HTTPCall object should have both ServerConf and Location. we should use them here:
```
Path matcher::rootToRequest(const HTTPCall &call)
{
	const ILocation *loc = requestToLocation(server->getConf(), req);
	if (call.location != NULL)
	{
		return (Path(call.location->getRoot()->get()));
	}
	return (Path(call.server->getRoot()->get()));
}
```

2023-09-11 07:27 UTC, arikhativa commented on src/code/matcher/matcher.cpp
> +bool matcher::isAutoIndexOnToRequest(const Server *server, const BasicHTTPRequest &req)
same

2023-09-11 07:27 UTC, arikhativa commented on src/code/matcher/matcher.cpp
> +bool matcher::canUploadToRequest(const Server *server, const BasicHTTPRequest &req)
same

2023-09-11 07:27 UTC, arikhativa commented on src/code/matcher/matcher.cpp
> +		if ((req.getPath().find((*it)->getPath().get()) == 0) || (req.getPath() == "" && (*it)->getPath().get() == "/"))
i dont understand the logic here.
these 2 "if"s are very confusing.
what are you trying to change? why `if ((*it)->getPath().get() == req.getPath())` does not work?

2023-09-11 09:32 UTC, arikhativa approved these changes

2023-09-11 09:34 UTC, merged